cliente_producto:
    resource: "@ClienteBundle/Controller/ProductoController.php"
    type:     annotation

cliente:
    resource: "@ClienteBundle/Resources/config/routing.yml"
    prefix:   /cliente

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
